"""
Report generator — converts an AnalysisReport to Markdown, HTML, or PDF.

Usage:
    from tibco_agent.report.generator import to_html, to_pdf
    html_bytes = to_html(report).encode()
    pdf_bytes  = to_pdf(report)
"""

from __future__ import annotations

import io
from datetime import datetime

import markdown as _md

from tibco_agent.analyzers.base import AnalysisReport, Severity

# ── HTML ──────────────────────────────────────────────────────────────────────

_HTML_CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       max-width: 960px; margin: 40px auto; padding: 0 24px;
       color: #1a1a2e; background: #fff; line-height: 1.6; }
h1   { color: #003865; border-bottom: 3px solid #003865; padding-bottom: 8px; }
h2   { color: #003865; margin-top: 2em; }
h3   { color: #0057a8; }
h4   { color: #444; }
table { border-collapse: collapse; width: 100%; margin: 1em 0; font-size: .9em; }
th    { background: #003865; color: #fff; padding: 8px 12px; text-align: left; }
td    { border: 1px solid #cde; padding: 7px 12px; }
tr:nth-child(even) { background: #f0f6ff; }
code  { background: #f4f4f8; border: 1px solid #dde; border-radius: 4px;
        padding: 2px 6px; font-size: .88em; color: #c7254e; }
pre   { background: #f4f4f8; border: 1px solid #dde; border-radius: 6px;
        padding: 14px; overflow-x: auto; }
pre code { background: none; border: none; padding: 0; color: #1a1a2e; }
blockquote { border-left: 4px solid #0057a8; margin: 0; padding: 8px 16px;
             background: #f0f6ff; color: #333; border-radius: 0 4px 4px 0; }
.badge-error   { background:#c0392b; color:#fff; border-radius:4px;
                 padding:2px 8px; font-size:.8em; margin-right:4px; }
.badge-warning { background:#e67e22; color:#fff; border-radius:4px;
                 padding:2px 8px; font-size:.8em; margin-right:4px; }
.badge-good    { background:#27ae60; color:#fff; border-radius:4px;
                 padding:2px 8px; font-size:.8em; margin-right:4px; }
.footer { margin-top: 3em; font-size: .8em; color: #999; border-top: 1px solid #eee;
          padding-top: 12px; }
"""

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>{css}</style>
</head>
<body>
<h1>TARA — Integration Analysis Report</h1>
<p><strong>File:</strong> {source} &nbsp;|&nbsp;
   <strong>Generated:</strong> {generated} &nbsp;|&nbsp;
   <span class="badge-error">{errors} error(s)</span>
   <span class="badge-warning">{warnings} warning(s)</span>
   <span class="badge-good">{positives} strength(s)</span>
</p>
{body}
<div class="footer">Generated by TARA — TIBCO AI Review Agent</div>
</body>
</html>
"""


def to_html(report: AnalysisReport) -> str:
    """Return a self-contained styled HTML string for the report."""
    body = _md.markdown(
        report.to_markdown(),
        extensions=["tables", "fenced_code", "nl2br"],
    )
    return _HTML_TEMPLATE.format(
        title=f"Report — {report.source}",
        css=_HTML_CSS,
        source=report.source,
        generated=datetime.now().strftime("%Y-%m-%d %H:%M"),
        errors=report.error_count,
        warnings=report.warning_count,
        positives=len(report.positives),
        body=body,
    )


# ── PDF ───────────────────────────────────────────────────────────────────────

def to_pdf(report: AnalysisReport) -> bytes:
    """Return a PDF byte string built directly from report fields (reportlab)."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()
    BLUE  = colors.HexColor("#003865")
    LBLUE = colors.HexColor("#0057a8")
    RED   = colors.HexColor("#c0392b")
    ORG   = colors.HexColor("#e67e22")
    GRN   = colors.HexColor("#27ae60")
    LGREY = colors.HexColor("#f4f4f8")

    def style(name, **kw) -> ParagraphStyle:
        base = styles[name]
        return ParagraphStyle(f"_custom_{id(kw)}", parent=base, **kw)

    h1  = style("Heading1", textColor=BLUE,  fontSize=16, spaceAfter=6)
    h2  = style("Heading2", textColor=BLUE,  fontSize=13, spaceBefore=14, spaceAfter=4)
    h3  = style("Heading3", textColor=LBLUE, fontSize=11, spaceBefore=8,  spaceAfter=3)
    body= style("Normal",   fontSize=9,  leading=13, spaceAfter=3)
    mono= style("Code",     fontName="Courier", fontSize=8, backColor=LGREY,
                borderPadding=4, leading=11)
    meta= style("Normal",   fontSize=8,  textColor=colors.grey)

    def hr(): return HRFlowable(width="100%", thickness=1, color=colors.lightgrey,
                                spaceAfter=6, spaceBefore=2)
    def sp(n=6): return Spacer(1, n)

    story = []

    # ── Title ──
    story.append(Paragraph("TARA — Integration Analysis Report", h1))
    story.append(hr())
    story.append(Paragraph(
        f"<b>File:</b> {report.source} &nbsp;&nbsp; "
        f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')} &nbsp;&nbsp; "
        f"<b>Errors:</b> {report.error_count} &nbsp; "
        f"<b>Warnings:</b> {report.warning_count} &nbsp; "
        f"<b>Strengths:</b> {len(report.positives)}",
        meta,
    ))
    story.append(sp(12))

    ov = report.overview
    if ov:
        # ── Overview ──
        story.append(Paragraph("Overview", h2))
        if ov.get("description"):
            story.append(Paragraph(ov["description"], body))
        info = []
        for label, key in [("Version", "version"), ("Pattern", "pattern"),
                            ("Flows", "flow_count"), ("Trigger port", "trigger_port")]:
            if ov.get(key):
                info.append([Paragraph(f"<b>{label}</b>", body),
                              Paragraph(str(ov[key]), body)])
        if info:
            t = Table(info, colWidths=[4*cm, 12*cm])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, -1), LGREY),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(t)
            story.append(sp())

        # Endpoints table
        eps = ov.get("endpoints", [])
        if eps:
            story.append(Paragraph("API Endpoints", h3))
            hdr = [Paragraph(c, style("Normal", textColor=colors.white, fontSize=8,
                                      fontName="Helvetica-Bold"))
                   for c in ["Method", "Path", "Flow", "Description"]]
            rows = [hdr] + [
                [Paragraph(e.get("method",""), body),
                 Paragraph(e.get("path",""), mono),
                 Paragraph(e.get("flow",""), mono),
                 Paragraph((e.get("description") or "")[:80], body)]
                for e in eps
            ]
            t = Table(rows, colWidths=[2*cm, 5*cm, 4*cm, 6*cm])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), BLUE),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LGREY]),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]))
            story.append(t)
            story.append(sp())

        # Tech stack
        tech = ov.get("technologies", [])
        if tech:
            story.append(Paragraph("Technology Stack", h3))
            for t_ in tech:
                story.append(Paragraph(f"• {t_}", body))
            story.append(sp())

    # ── Strengths ──
    if report.positives:
        story.append(Paragraph("Strengths", h2))
        for p in report.positives:
            story.append(Paragraph(f"<b>[{p.rule_id}] {p.title}</b>", h3))
            story.append(Paragraph(p.message, body))

    # ── Issues ──
    errors   = [f for f in report.findings if f.severity == Severity.ERROR]
    warnings = [f for f in report.findings if f.severity == Severity.WARNING]
    infos    = [f for f in report.findings if f.severity == Severity.INFO]

    if report.findings:
        story.append(Paragraph("Issues", h2))
        for group, label, color in [
            (errors,   "Errors",   RED),
            (warnings, "Warnings", ORG),
            (infos,    "Info",     LBLUE),
        ]:
            if not group:
                continue
            story.append(Paragraph(label, h3))
            for f in group:
                story.append(Paragraph(
                    f'<font color="#{color.hexval()[2:]}"><b>[{f.rule_id}]</b></font> '
                    f'<b>{f.title}</b>', body))
                story.append(Paragraph(f"<i>Location:</i> {f.location}", body))
                story.append(Paragraph(f.message, body))
                story.append(Paragraph(f"<b>Fix:</b> {f.recommendation}", body))
                story.append(sp(4))

    # ── Observations ──
    if report.observations:
        story.append(Paragraph("Observations", h2))
        for obs in report.observations:
            story.append(Paragraph(f"• {obs}", body))

    # ── Footer ──
    story.append(sp(16))
    story.append(hr())
    story.append(Paragraph("Generated by TARA — TIBCO AI Review Agent", meta))

    doc.build(story)
    return buf.getvalue()
